In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

In [6]:
#list, array
lst =[1,2,3,4,5,6]
arr = np.array([1,2,3,4,5,6])
print("list:", lst)
print("array", arr)


list: [1, 2, 3, 4, 5, 6]
array [1 2 3 4 5 6]


In [8]:

lst = [1, 2, 3, 4, 5, 6]

arr = np.array([1, 2, 3, 4, 5, 6])

print("List:", lst)
print("Type of list:", type(lst))

print("Array:", arr)
print("Type of array:", type(arr))


List: [1, 2, 3, 4, 5, 6]
Type of list: <class 'list'>
Array: [1 2 3 4 5 6]
Type of array: <class 'numpy.ndarray'>


In [7]:
arr =np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
arr=np.arange(1,21)
# print("array",arr)
arr



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
lst = list(range(1, 21))
# print("List:", lst)
lst


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)
np.ones((5,10))


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)
np.ones((5,10))


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1]:
import numpy as np

arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [2]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
#ld array convert into 2d array
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [7]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [9]:
arr=np.random.randint(1,5,9)
arr

array([2, 3, 3, 1, 4, 1, 4, 4, 4], dtype=int32)

In [10]:
arr=np.random.randint(1,5,(3,3))
arr

array([[4, 1, 4],
       [3, 4, 4],
       [4, 1, 1]], dtype=int32)

In [12]:
arr=np.random.random(10)
arr

array([0.83133234, 0.2700186 , 0.29042357, 0.70644263, 0.83631018,
       0.45856513, 0.16589938, 0.83290918, 0.94191243, 0.10501858])

In [14]:
arr=np.random.random((5,10))
arr

array([[0.58007787, 0.2345337 , 0.5177028 , 0.48675868, 0.9184661 ,
        0.47686066, 0.41620418, 0.08409521, 0.34602981, 0.31259755],
       [0.88325422, 0.38984132, 0.76374573, 0.10115151, 0.29495099,
        0.86578517, 0.19362587, 0.4876703 , 0.31859373, 0.46045838],
       [0.60148159, 0.96073359, 0.60191363, 0.36222518, 0.5620066 ,
        0.66730748, 0.79755993, 0.61750732, 0.89110832, 0.67278337],
       [0.88940396, 0.95312971, 0.10175637, 0.07148357, 0.53079534,
        0.49386879, 0.78395004, 0.61420818, 0.52073828, 0.19204081],
       [0.28462216, 0.4307733 , 0.31523825, 0.80266505, 0.40712876,
        0.25114719, 0.58812566, 0.7008926 , 0.72945439, 0.33540284]])

In [16]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [17]:
arr.shape
arr.size
print("size of array", arr.size)
print("shape of array", arr.shape)
print("type of array", arr.dtype)
print("number of dimension", arr.ndim)


size of array 60
shape of array (12, 5)
type of array int64
number of dimension 2


In [18]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [19]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

| Feature                | `flatten()`               | `ravel()`              |
| ---------------------- | ------------------------- | ---------------------- |
| **Returns**            | **Copy** (new array)      | **View** (if possible) |
| **Modifies original?** | ❌ No                      | ✅ Sometimes (if view)  |
| **Memory**             | Uses more memory          | More memory-efficient  |
| **Writable?**          | Independent from original | May reflect changes    |
| **Speed**              | Slightly slower           | Faster                 |


In [20]:
arr.shape

(12, 5)

In [21]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [22]:
arr.T.shape

(5, 12)

In [24]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [26]:
arr[0:12]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [28]:
arr[1,1]

np.int64(6)

In [30]:
arr[1,3:5]

array([8, 9])

In [31]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [33]:
arr[1,1]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [34]:
arr[11,4]

np.int64(59)

In [35]:
arr[-1]

array([55, 56, 57, 58, 59])

In [36]:
arr[-1,-1]

np.int64(59)

In [75]:
arr=np.array(np.arange(225)).reshape(5,15,3)

In [76]:
arr.ndim, arr.shape, arr.size, arr.argmax

(3, (5, 15, 3), 225, <function ndarray.argmax>)

In [77]:
arr[0,2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [78]:
arr[0,2:2]


array([], shape=(0, 3), dtype=int64)

In [79]:
arr[0,3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [80]:
arr[-1]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [85]:
arr[:,0:1,0:1]


array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [82]:
arr[0,1,1]

np.int64(4)

In [83]:
np.array([1,5,6,9,2,3])



array([1, 5, 6, 9, 2, 3])

In [87]:
arr.sort()

In [88]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [9]:
arr =np.array([1,2,3,5])


NameError: name 'np' is not defined

In [2]:
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([1,6,3,5])

NameError: name 'np' is not defined

In [3]:
arr1+arr2
arr1+arr2
arr1-arr2

NameError: name 'arr1' is not defined